apiVersion: apps/v1
kind: Deployment
metadata:
  name: herbert-backend
  labels:
    app: herbert-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: herbert-backend
  template:
    metadata:
      labels:
        app: herbert-backend
    spec:
      containers:
        - name: herbert-backend
          image: jp0606/herbert-backend:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 80
              protocol: TCP
          env:
            - name: DB_CONNECTION_STRING
              value: "Host=postgres-service.default.svc.cluster.local;Port=5432;Database=herbert-database;Username=postgres;Password=postgres"
            - name: Logging__LogLevel__Default
              value: "Information"
            - name: Logging__LogLevel__Microsoft.AspNetCore
              value: "Warning"
            - name: AllowedHosts
              value: "*"
---
apiVersion: v1
kind: Service
metadata:
  name: herbert-backend-service
spec:
  type: NodePort
  selector:
    app: herbert-backend
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30001