apiVersion: apps/v1
kind: Deployment
metadata:
  name: herbert-backend
  labels:
    app: herbert-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: herbert-backend
  template:
    metadata:
      name: herbert-backend
      labels:
        app: herbert-backend
    spec:
      containers:
        - name: herbert-backend
          image: backend:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
              protocol: TCP
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: herbert-backend-service
spec:
  selector:
    app: herbert-backend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: herbert-backend-service
spec:
  type: NodePort
  selector:
    app: herbert-backend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30001 
