name: .NET

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Print Repository Contents
      run: ls -R

    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: '8.0.x'

    - name: Restore dependencies
      run: dotnet restore backend.sln

    - name: Build Solution
      run: dotnet build backend.sln --no-restore

    - name: Find Test Project
      run: |
        TESTS_PROJECT=$(find . -name "Tests.csproj" -print -quit)
        echo "Found Test Project: $TESTS_PROJECT"
        echo "##[set-output name=TESTS_PROJECT;]$TESTS_PROJECT"

    - name: Test
      run: dotnet test ${{ env.TESTS_PROJECT }} --no-build --verbosity normal
