name: Start PostgreSQL in Kubernetes

on:
  workflow_dispatch:

jobs:
  start-postgres:
    name: Start PostgreSQL Database
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v3

      - name: Set up kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: 'latest'

      - name: Authenticate with Kubernetes cluster
        env:
          KUBECONFIG: ${{ secrets.KUBECONFIG }}
        run: |
          echo "$KUBECONFIG" > ~/.kube/config

      - name: Apply PostgreSQL configuration
        run: |
          kubectl apply -f ./Backend/k8s/postgres.yaml

      - name: Verify Pod status
        run: |
          kubectl get pods --selector=app=postgres
